### ISSUE TITLE
loader change to get MGI URLs to work

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-legacy#1]
woohoo, a ticket on this tracker!

We need a workaround for the fact that MGI is special. For reasons that do my head in, they need the "MGI:" prefix to go in URLs, and for further reasons (see above) the way they make it work for GO xref URL syntax is to put the prefix in twice in the GAF with/from field. Yep, it actually has "MGI:MGI:" in column 8, and, as we found in https://github.com/pombase/curation/issues/2278, we have to do the same for our links to work. 

I tried just changing "MGI:" to "MGI:MGI:" in the contig files, but that makes errors appear in the qualifier_problems.txt log (understandably enough, the loader is configured for the vast majority of cases where prefix:prefix:id is a mistake), e.g.

    mRNA SPAC22F3.10c.1: with value "MGI:MGI:104990" should be in the form "DB:ACCESSION": failed to load qualifier 'aspect=C; term=glutamate-cysteine ligase complex; GOid=GO:0017109; evidence=ISO; db_xref=GO_REF:0000024; with=MGI:MGI:104990; date=20070111' from SPAC22F3.10c.1:

So it looks like we have two options:

1. change the contig file loader to recognize "MGI:MGI:accession" as legit; or
2. change whatever else would need changing to get a URL like "http://www.informatics.jax.org/accession/MGI:80863" when we have "MGI:acc" in the contig file.

I have no preference; just let me know what should be in the contig files (for now, I'll change back to one "MGI:" so the rest of the annotation will load, but it would only take seconds to double up again if you pick option 1).

**Comment by kimrutherford** [comment]
It looks like the MGI links work now.  I checked this page:
 https://www.pombase.org/gene/SPAC664.08c
